"""add_tbl_refresh_token table

Revision ID: 4ab734709789
Revises: dbb7e520f2c9
Create Date: 2023-08-23 10:38:37.629119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ab734709789'
down_revision = 'dbb7e520f2c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_refresh_token',
    sa.Column('refresh_token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('device', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_users.user_id'], ),
    sa.PrimaryKeyConstraint('refresh_token')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_refresh_token')
    # ### end Alembic commands ###
