"""change_pk_of_tbl_refresh_token table

Revision ID: 8376e4401db1
Revises: d13b132cfeb4
Create Date: 2023-08-23 13:44:37.463758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8376e4401db1'
down_revision = 'd13b132cfeb4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbl_refresh_token', 'refresh_token',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbl_refresh_token', 'refresh_token',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
