"""update_tbl_refresh_token table

Revision ID: d13b132cfeb4
Revises: 4f84a28c3a3f
Create Date: 2023-08-23 11:01:08.627017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd13b132cfeb4'
down_revision = '4f84a28c3a3f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
