"""update user field

Revision ID: dbb7e520f2c9
Revises: fe68aeb48434
Create Date: 2023-08-16 14:19:50.115373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbb7e520f2c9'
down_revision = 'fe68aeb48434'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE IF EXISTS tbl_users RENAME password_hash TO hashed_password;")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE IF EXISTS tbl_users RENAME hashed_password TO password_hash;")

    # ### end Alembic commands ###
