"""initial_migration

Revision ID: fe68aeb48434
Revises: 
Create Date: 2023-08-16 13:42:11.823129

"""
import uuid

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from migration.default_data import DEFAULT_USER_ROLES, DEFAULT_USERS, DEFAULT_ROLES

# revision identifiers, used by Alembic.
revision = 'fe68aeb48434'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_roles',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tbl_users',
    sa.Column('user_id', postgresql.UUID(as_uuid=True), default=uuid.uuid4(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_role_association',
    sa.Column('user_id', postgresql.UUID(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['tbl_roles.role_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    # ### end Alembic commands ###

    for role in DEFAULT_ROLES:
        op.execute("INSERT INTO tbl_roles (name) VALUES ('{}')".format(role['name']))

    for user in DEFAULT_USERS:
        op  .execute(
            "INSERT INTO tbl_users (user_id, username, email, password_hash, is_active) VALUES ('{}', '{}', '{}', '{}', '{}')".format(
                user['user_id'], user['username'], user['email'], user['password_hash'], user['is_active']))

    for roles in DEFAULT_USER_ROLES:
        op.execute(
            "INSERT INTO user_role_association (user_id, role_id) VALUES ('{}', '{}')".format(
                roles['user_id'], roles['role_id']))



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_role_association')
    op.drop_table('tbl_users')
    op.drop_table('tbl_roles')
    # ### end Alembic commands ###
